"""Extra recipe catalog entries for meal landing site (39 recipes)."""

RECIPES = [
    {'slug': 'carbonara',
     'id': 'extra-01',
     'name': 'カルボナーラ',
     'category': 'main',
     'timeMinutes': 25,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': 'ベーコン', 'qty': '80g'},
                     {'name': '卵', 'qty': '2個'},
                     {'name': 'パルメザンチーズ', 'qty': '大さじ3'},
                     {'name': '黒胡椒', 'qty': 'たっぷり'}],
     'steps': [{'label': '準備', 'text': 'ベーコンは1cm幅に切る。ボウルに卵・すりおろしチーズ・黒胡椒を入れてよく混ぜ、ソースにしておく。'},
               {'label': '加熱', 'text': '大きめの鍋でパスタを表示時間より1分短く茹でる。別のフライパンでベーコンを中火でカリカリになるまで炒める。'},
               {'label': '仕上げ', 'text': '茹で上がったパスタをフライパンに入れ、火を止めてからソースを回し入れ、余熱でとろみをつける。器に盛り、追いチーズと胡椒を振る。'}]},
    {'slug': 'meat-sauce-pasta',
     'id': 'extra-02',
     'name': 'ミートソースパスタ',
     'category': 'main',
     'timeMinutes': 35,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': '合いびき肉', 'qty': '150g'},
                     {'name': '玉ねぎ', 'qty': '1/2個'},
                     {'name': 'にんじん', 'qty': '1/2本'},
                     {'name': 'トマト缶', 'qty': '1缶'},
                     {'name': 'にんにく', 'qty': '1片'}],
     'steps': [{'label': '準備', 'text': '玉ねぎとにんじんはみじん切り、にんにくは薄切りにする。'},
               {'label': '加熱', 'text': 'オリーブ油でにんにくを香り出し、野菜を炒めてから合いびき肉を加え、色が変わるまで炒める。トマト缶を入れ、とろみがつくまで20分ほど煮込む。'},
               {'label': '仕上げ', 'text': '別鍋でパスタを茹で、ソースと絡めて盛りつける。'}]},
    {'slug': 'peperoncino',
     'id': 'extra-03',
     'name': 'ペペロンチーノ',
     'category': 'main',
     'timeMinutes': 20,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': 'にんにく', 'qty': '2片'},
                     {'name': '唐辛子', 'qty': '2本'},
                     {'name': 'オリーブ油', 'qty': '大さじ4'},
                     {'name': 'パセリ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': 'にんにくは薄切り、唐辛子は輪切りにする。パセリはみじん切りにしておく。'},
               {'label': '加熱', 'text': 'フライパンにオリーブ油とにんにく・唐辛子を入れ、弱火で香りを出す。茹で上がったパスタと茹で汁を少し加え、全体を絡める。'},
               {'label': '仕上げ', 'text': '塩で味を整え、パセリを散らして皿に盛る。'}]},
    {'slug': 'napolitan',
     'id': 'extra-04',
     'name': 'ナポリタン',
     'category': 'main',
     'timeMinutes': 25,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': 'ウインナー', 'qty': '4本'},
                     {'name': '玉ねぎ', 'qty': '1/4個'},
                     {'name': 'ピーマン', 'qty': '1個'},
                     {'name': 'ケチャップ', 'qty': '大さじ5'}],
     'steps': [{'label': '準備', 'text': '玉ねぎとピーマン、ウインナーは食べやすい大きさに切る。パスタは少し太めに茹でておく。'},
               {'label': '加熱', 'text': 'フライパンでウインナーと野菜を炒め、ケチャップを加えて軽く煮詰める。パスタを入れて全体を炒め合わせる。'},
               {'label': '仕上げ', 'text': '皿に盛り、好みで粉チーズをかける。'}]},
    {'slug': 'aglio-olio',
     'id': 'extra-05',
     'name': 'アーリオ・オーリオ',
     'category': 'main',
     'timeMinutes': 18,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': 'にんにく', 'qty': '3片'},
                     {'name': 'オリーブ油', 'qty': '大さじ5'},
                     {'name': '唐辛子', 'qty': '1本'},
                     {'name': 'パセリ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': 'にんにくは薄切り、唐辛子は種を除いて輪切りにする。'},
               {'label': '加熱', 'text': 'フライパンにオリーブ油とにんにくを入れ、弱火で色づく前に香りを出す。茹でたパスタと茹で汁を加え、軽く和える。'},
               {'label': '仕上げ', 'text': '塩で味を調え、パセリを散らして完成。'}]},
    {'slug': 'tomato-cream-pasta',
     'id': 'extra-06',
     'name': 'トマトクリームパスタ',
     'category': 'main',
     'timeMinutes': 25,
     'tags': ['パスタ', '洋食'],
     'servings': 2,
     'ingredients': [{'name': 'スパゲッティ', 'qty': '200g'},
                     {'name': 'ベーコン', 'qty': '60g'},
                     {'name': 'トマト缶', 'qty': '1/2缶'},
                     {'name': '生クリーム', 'qty': '100ml'},
                     {'name': 'にんにく', 'qty': '1片'}],
     'steps': [{'label': '準備', 'text': 'ベーコンは1cm幅に切り、にんにくは薄切りにする。'},
               {'label': '加熱', 'text': 'フライパンでベーコンとにんにくを炒め、トマト缶を加えて5分煮込む。生クリームを入れて軽く煮立たせる。'},
               {'label': '仕上げ', 'text': '茹でたパスタを絡め、塩胡椒で味を整えて盛りつける。'}]},
    {'slug': 'hamburg-steak',
     'id': 'extra-07',
     'name': 'ハンバーグ',
     'category': 'main',
     'timeMinutes': 30,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': '合いびき肉', 'qty': '300g'},
                     {'name': '玉ねぎ', 'qty': '1/2個'},
                     {'name': 'パン粉', 'qty': '大さじ3'},
                     {'name': '卵', 'qty': '1個'},
                     {'name': 'ケチャップ', 'qty': '大さじ2'},
                     {'name': 'ウスターソース', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': '玉ねぎはみじん切りにしてレンジで2分加熱し、水気を切る。合いびき肉・パン粉・卵・塩胡椒を混ぜ、空気を抜きながら丸く成形する。'},
               {'label': '加熱', 'text': 'フライパンに油を熱し、中火で両面に焼き色をつける。弱火にして蓋をし、中まで火を通す。'},
               {'label': '仕上げ', 'text': 'ケチャップとウスターソースを合わせたソースを絡め、皿に盛る。'}]},
    {'slug': 'omurice',
     'id': 'extra-08',
     'name': 'オムライス',
     'category': 'main',
     'timeMinutes': 30,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': 'ごはん', 'qty': '茶碗2杯分'},
                     {'name': '鶏もも肉', 'qty': '80g'},
                     {'name': '玉ねぎ', 'qty': '1/4個'},
                     {'name': '卵', 'qty': '3個'},
                     {'name': 'ケチャップ', 'qty': '大さじ4'}],
     'steps': [{'label': '準備', 'text': '鶏肉と玉ねぎを細かく切る。フライパンで炒め、ごはんとケチャップを加えてチキンライスを作る。'},
               {'label': '加熱', 'text': '別のフライパンで卵液を半熟の薄焼き卵にし、チキンライスを包む形で巻く。'},
               {'label': '仕上げ', 'text': '皿にのせ、ケチャップで飾り切りを描く。'}]},
    {'slug': 'cream-stew',
     'id': 'extra-09',
     'name': 'クリームシチュー',
     'category': 'main',
     'timeMinutes': 40,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': '鶏もも肉', 'qty': '200g'},
                     {'name': 'じゃがいも', 'qty': '2個'},
                     {'name': 'にんじん', 'qty': '1/2本'},
                     {'name': '玉ねぎ', 'qty': '1/2個'},
                     {'name': 'ルウ', 'qty': '1/2箱'},
                     {'name': '牛乳', 'qty': '400ml'}],
     'steps': [{'label': '準備', 'text': '鶏肉と野菜は一口大に切る。'},
               {'label': '加熱', 'text': '鍋で鶏肉と野菜を炒め、水400mlを加えて15分煮込む。ルウを溶き入れ、牛乳を加えてとろみをつける。'},
               {'label': '仕上げ', 'text': '塩胡椒で味を整え、器に盛る。'}]},
    {'slug': 'potato-gratin',
     'id': 'extra-10',
     'name': 'ポテトグラタン',
     'category': 'side',
     'timeMinutes': 45,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': 'じゃがいも', 'qty': '3個'},
                     {'name': 'ベーコン', 'qty': '60g'},
                     {'name': '玉ねぎ', 'qty': '1/4個'},
                     {'name': '牛乳', 'qty': '200ml'},
                     {'name': 'チーズ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': 'じゃがいもは薄切りにし、水にさらして水気を切る。ベーコンと玉ねぎは細かく切る。'},
               {'label': '加熱', 'text': '耐熱皿にじゃがいも・ベーコン・玉ねぎを重ね、牛乳を注ぎ、アルミホイルをしてオーブンまたはトースターで20分加熱する。'},
               {'label': '仕上げ', 'text': 'チーズをのせてさらに焼き色がつくまで加熱し、完成。'}]},
    {'slug': 'beef-stew',
     'id': 'extra-11',
     'name': 'ビーフシチュー',
     'category': 'main',
     'timeMinutes': 90,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': '牛もも肉', 'qty': '300g'},
                     {'name': '玉ねぎ', 'qty': '1個'},
                     {'name': 'にんじん', 'qty': '1本'},
                     {'name': 'じゃがいも', 'qty': '2個'},
                     {'name': '赤ワイン', 'qty': '100ml'},
                     {'name': 'デミグラスソース', 'qty': '1缶'}],
     'steps': [{'label': '準備', 'text': '牛肉は一口大、野菜は大きめに切る。肉に小麦粉を薄くまぶす。'},
               {'label': '加熱', 'text': '鍋で肉をこんがり焼き、野菜を加えて炒める。赤ワインと水を入れ、弱火で60分煮込む。デミグラスソースを加えてとろみをつける。'},
               {'label': '仕上げ', 'text': '塩胡椒で味を整え、器に盛る。'}]},
    {'slug': 'doria',
     'id': 'extra-12',
     'name': 'ドリア',
     'category': 'main',
     'timeMinutes': 35,
     'tags': ['洋食'],
     'servings': 2,
     'ingredients': [{'name': 'ごはん', 'qty': '茶碗2杯分'},
                     {'name': '合いびき肉', 'qty': '100g'},
                     {'name': '玉ねぎ', 'qty': '1/4個'},
                     {'name': 'バター', 'qty': '20g'},
                     {'name': 'ホワイトソース', 'qty': '200ml'},
                     {'name': 'チーズ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': '玉ねぎと合いびき肉を炒め、バターとケチャップで味付けしたライスを作る。'},
               {'label': '加熱', 'text': '耐熱皿にライスを敷き、ホワイトソースをかける。'},
               {'label': '仕上げ', 'text': 'チーズをのせてトースターで5分ほど焼き、焦げ目がついたら完成。'}]},
    {'slug': 'nikujaga',
     'id': 'extra-13',
     'name': '肉じゃが',
     'category': 'main',
     'timeMinutes': 35,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '牛肉薄切り', 'qty': '150g'},
                     {'name': 'じゃがいも', 'qty': '3個'},
                     {'name': 'にんじん', 'qty': '1/2本'},
                     {'name': '玉ねぎ', 'qty': '1/2個'},
                     {'name': 'だし', 'qty': '300ml'},
                     {'name': '醤油', 'qty': '大さじ3'}],
     'steps': [{'label': '準備', 'text': 'じゃがいも・にんじんは一口大、玉ねぎはくし形に切る。'},
               {'label': '加熱', 'text': '鍋にだし・醤油・みりん・砂糖を入れ、野菜と肉を加えて弱火で20分煮る。'},
               {'label': '仕上げ', 'text': '汁気が少なくなったら火を止め、味をなじませる。'}]},
    {'slug': 'miso-salmon',
     'id': 'extra-14',
     'name': '鮭の味噌焼き',
     'category': 'main',
     'timeMinutes': 20,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '鮭切り身', 'qty': '2切れ'},
                     {'name': '味噌', 'qty': '大さじ2'},
                     {'name': 'みりん', 'qty': '大さじ2'},
                     {'name': '酒', 'qty': '大さじ1'},
                     {'name': '砂糖', 'qty': '小さじ1'}],
     'steps': [{'label': '準備', 'text': '味噌・みりん・酒・砂糖を混ぜて味噌ダレを作る。鮭の水気を拭き取る。'},
               {'label': '加熱', 'text': 'フライパンに油を熱し、鮭を中火で皮目から焼く。裏返して火を通す。'},
               {'label': '仕上げ', 'text': '味噌ダレを絡め、とろみがついたら完成。'}]},
    {'slug': 'tamagoyaki',
     'id': 'extra-15',
     'name': '卵焼き',
     'category': 'side',
     'timeMinutes': 15,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '卵', 'qty': '3個'},
                     {'name': 'だし', 'qty': '大さじ2'},
                     {'name': '醤油', 'qty': '小さじ1'},
                     {'name': '砂糖', 'qty': '小さじ2'},
                     {'name': 'サラダ油', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': '卵を溶き、だし・醤油・砂糖を加えて混ぜる。'},
               {'label': '加熱', 'text': '卵焼き用フライパンに油を薄く引き、卵液を何度か巻きながら焼く。'},
               {'label': '仕上げ', 'text': '形を整えて冷まし、食べやすく切って盛る。'}]},
    {'slug': 'tonkatsu',
     'id': 'extra-16',
     'name': 'とんかつ',
     'category': 'main',
     'timeMinutes': 30,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '豚ロース', 'qty': '2枚'},
                     {'name': '小麦粉', 'qty': '適量'},
                     {'name': '卵', 'qty': '1個'},
                     {'name': 'パン粉', 'qty': '適量'},
                     {'name': 'キャベツ', 'qty': '2枚'}],
     'steps': [{'label': '準備', 'text': '豚肉の筋を切り、塩胡椒をする。小麦粉・溶き卵・パン粉の順に衣をつける。キャベツは千切りにする。'},
               {'label': '加熱', 'text': '170度の油で3〜4分揚げ、一度取り出して余熱で火を通す。'},
               {'label': '仕上げ', 'text': '再び揚げてカラッとさせ、キャベツと一緒に盛る。'}]},
    {'slug': 'gyoza',
     'id': 'extra-17',
     'name': '餃子',
     'category': 'main',
     'timeMinutes': 40,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '豚ひき肉', 'qty': '200g'},
                     {'name': 'キャベツ', 'qty': '100g'},
                     {'name': 'にら', 'qty': '1/4束'},
                     {'name': '餃子の皮', 'qty': '24枚'},
                     {'name': '醤油', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': 'キャベツは塩もみして水気を切り、にらと豚肉・醤油・ごま油を混ぜてタネを作る。皮に包む。'},
               {'label': '加熱', 'text': 'フライパンに油を熱し、餃子を並べて焼き色をつける。水を加え蓋をして蒸し焼きにする。'},
               {'label': '仕上げ', 'text': '水分が飛んだらごま油を回しかけ、パリッと仕上げる。'}]},
    {'slug': 'yakisoba',
     'id': 'extra-18',
     'name': '焼きそば',
     'category': 'main',
     'timeMinutes': 20,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '蒸しそば', 'qty': '2玉'},
                     {'name': '豚バラ肉', 'qty': '100g'},
                     {'name': 'キャベツ', 'qty': '1/4個'},
                     {'name': 'もやし', 'qty': '1/2袋'},
                     {'name': '焼きそばソース', 'qty': '大さじ3'}],
     'steps': [{'label': '準備', 'text': 'キャベツはざっくり切り、豚肉は食べやすい大きさにする。'},
               {'label': '加熱', 'text': 'フライパンで豚肉と野菜を炒め、蒸しそばを加えてほぐしながら炒める。'},
               {'label': '仕上げ', 'text': 'ソースを絡め、好みで紅生姜を添える。'}]},
    {'slug': 'curry-rice',
     'id': 'extra-19',
     'name': 'カレーライス',
     'category': 'main',
     'timeMinutes': 45,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '豚肉', 'qty': '200g'},
                     {'name': '玉ねぎ', 'qty': '1個'},
                     {'name': 'にんじん', 'qty': '1本'},
                     {'name': 'じゃがいも', 'qty': '2個'},
                     {'name': 'カレールウ', 'qty': '1/2箱'}],
     'steps': [{'label': '準備', 'text': '野菜と肉は一口大に切る。'},
               {'label': '加熱', 'text': '鍋で肉と野菜を炒め、水500mlを加えて柔らかくなるまで煮込む。ルウを溶き入れる。'},
               {'label': '仕上げ', 'text': 'ごはんを盛り、カレーをかけて完成。'}]},
    {'slug': 'fried-rice',
     'id': 'extra-20',
     'name': 'チャーハン',
     'category': 'main',
     'timeMinutes': 15,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'ごはん', 'qty': '茶碗2杯分'},
                     {'name': '卵', 'qty': '2個'},
                     {'name': 'ハム', 'qty': '2枚'},
                     {'name': '長ねぎ', 'qty': '1/2本'},
                     {'name': '醤油', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': 'ハムと長ねぎは細かく切る。ごはんはほぐしておく。'},
               {'label': '加熱', 'text': 'フライパンで卵を半熟に炒め、ごはんを加えてパラパラになるまで炒める。'},
               {'label': '仕上げ', 'text': 'ハム・ねぎ・醤油を加え、全体を炒め合わせる。'}]},
    {'slug': 'chikuzenni',
     'id': 'extra-21',
     'name': '筑前煮',
     'category': 'main',
     'timeMinutes': 40,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '鶏もも肉', 'qty': '200g'},
                     {'name': 'れんこん', 'qty': '100g'},
                     {'name': 'にんじん', 'qty': '1/2本'},
                     {'name': 'しいたけ', 'qty': '3個'},
                     {'name': '醤油', 'qty': '大さじ3'},
                     {'name': 'みりん', 'qty': '大さじ3'}],
     'steps': [{'label': '準備', 'text': '鶏肉と野菜は食べやすい大きさに切る。れんこんは酢水にさらす。'},
               {'label': '加熱', 'text': '鍋にだし・調味料を入れ、材料を並べて落とし蓋をし、弱火で30分煮る。'},
               {'label': '仕上げ', 'text': '汁気が少なくなったら火を止め、味をなじませる。'}]},
    {'slug': 'saba-misoni',
     'id': 'extra-22',
     'name': 'サバの味噌煮',
     'category': 'main',
     'timeMinutes': 30,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'サバ切り身', 'qty': '2切れ'},
                     {'name': '味噌', 'qty': '大さじ2'},
                     {'name': 'みりん', 'qty': '大さじ2'},
                     {'name': '酒', 'qty': '大さじ2'},
                     {'name': '生姜', 'qty': '1片'}],
     'steps': [{'label': '準備', 'text': 'サバの水気を拭き取り、生姜は薄切りにする。'},
               {'label': '加熱', 'text': '鍋に酒・みりん・味噌・砂糖を入れて煮立て、サバを皮目を上にして入れる。落とし蓋をして中火で15分煮る。'},
               {'label': '仕上げ', 'text': '汁をかけながら煮詰め、照りが出たら完成。'}]},
    {'slug': 'niku-daikon',
     'id': 'extra-23',
     'name': '肉大根',
     'category': 'main',
     'timeMinutes': 35,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '豚バラ肉', 'qty': '150g'},
                     {'name': '大根', 'qty': '1/4本'},
                     {'name': 'だし', 'qty': '300ml'},
                     {'name': '醤油', 'qty': '大さじ2'},
                     {'name': 'みりん', 'qty': '大さじ2'}],
     'steps': [{'label': '準備', 'text': '大根は厚めのいちょう切りにし、米のとぎ汁で下茹でする。豚肉は食べやすい大きさに切る。'},
               {'label': '加熱', 'text': '鍋にだしと調味料を入れ、大根と肉を加えて弱火で25分煮る。'},
               {'label': '仕上げ', 'text': '汁気が半分になったら火を止める。'}]},
    {'slug': 'nasu-miso',
     'id': 'extra-24',
     'name': 'なすの味噌炒め',
     'category': 'side',
     'timeMinutes': 15,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'なす', 'qty': '2本'},
                     {'name': '味噌', 'qty': '大さじ1'},
                     {'name': 'みりん', 'qty': '大さじ1'},
                     {'name': '砂糖', 'qty': '小さじ1'},
                     {'name': 'ごま油', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': 'なすは乱切りにし、水にさらして水気を切る。味噌・みりん・砂糖を合わせる。'},
               {'label': '加熱', 'text': 'フライパンにごま油を熱し、なすを炒める。'},
               {'label': '仕上げ', 'text': '味噌ダレを加えて絡め、器に盛る。'}]},
    {'slug': 'potato-salad',
     'id': 'extra-25',
     'name': 'ポテトサラダ',
     'category': 'side',
     'timeMinutes': 25,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'じゃがいも', 'qty': '3個'},
                     {'name': 'きゅうり', 'qty': '1本'},
                     {'name': 'ハム', 'qty': '2枚'},
                     {'name': 'マヨネーズ', 'qty': '大さじ3'},
                     {'name': '酢', 'qty': '小さじ1'}],
     'steps': [{'label': '準備', 'text': 'じゃがいもは茹でて潰し、きゅうりは薄切りにして塩もみする。ハムは細かく切る。'},
               {'label': '加熱', 'text': 'じゃがいもが温かいうちにマヨネーズと酢を混ぜる。'},
               {'label': '仕上げ', 'text': 'きゅうりとハムを加え、塩胡椒で味を整える。'}]},
    {'slug': 'sunomono',
     'id': 'extra-26',
     'name': '酢の物',
     'category': 'side',
     'timeMinutes': 10,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'きゅうり', 'qty': '1本'},
                     {'name': 'わかめ', 'qty': '30g'},
                     {'name': '酢', 'qty': '大さじ2'},
                     {'name': '砂糖', 'qty': '大さじ1'},
                     {'name': '醤油', 'qty': '小さじ1'}],
     'steps': [{'label': '準備', 'text': 'きゅうりは薄切りにし、塩もみして水気を切る。わかめは水で戻す。'},
               {'label': '加熱', 'text': '酢・砂糖・醤油を混ぜて甘酢を作る。'},
               {'label': '仕上げ', 'text': 'きゅうりとわかめを和え、冷やして盛る。'}]},
    {'slug': 'broccoli-shiraae',
     'id': 'extra-27',
     'name': 'ブロッコリーの白和え',
     'category': 'side',
     'timeMinutes': 15,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'ブロッコリー', 'qty': '1房'},
                     {'name': '豆腐', 'qty': '1/2丁'},
                     {'name': 'すりごま', 'qty': '大さじ1'},
                     {'name': '醤油', 'qty': '小さじ1'},
                     {'name': '砂糖', 'qty': '小さじ1'}],
     'steps': [{'label': '準備', 'text': 'ブロッコリーは小房に分け、豆腐は水切りして潰す。'},
               {'label': '加熱', 'text': 'ブロッコリーを茹でて冷水にとる。'},
               {'label': '仕上げ', 'text': '豆腐にすりごま・醤油・砂糖を混ぜ、ブロッコリーと和える。'}]},
    {'slug': 'wakame-salad',
     'id': 'extra-28',
     'name': 'わかめサラダ',
     'category': 'side',
     'timeMinutes': 10,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '乾燥わかめ', 'qty': '大さじ2'},
                     {'name': 'きゅうり', 'qty': '1/2本'},
                     {'name': '酢', 'qty': '大さじ1'},
                     {'name': 'ごま油', 'qty': '大さじ1'},
                     {'name': '醤油', 'qty': '小さじ1'}],
     'steps': [{'label': '準備', 'text': 'わかめは水で戻し、水気を切る。きゅうりは薄切りにする。'},
               {'label': '加熱', 'text': '酢・ごま油・醤油を混ぜてドレッシングを作る。'},
               {'label': '仕上げ', 'text': 'わかめときゅうりを和え、器に盛る。'}]},
    {'slug': 'kenchinjiru',
     'id': 'extra-29',
     'name': 'けんちん汁',
     'category': 'soup',
     'timeMinutes': 30,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '大根', 'qty': '1/4本'},
                     {'name': 'にんじん', 'qty': '1/2本'},
                     {'name': 'ごぼう', 'qty': '1/2本'},
                     {'name': '豆腐', 'qty': '1/2丁'},
                     {'name': '味噌', 'qty': '大さじ2'}],
     'steps': [{'label': '準備', 'text': '野菜は細切り、豆腐は角切りにする。ごぼうは水にさらす。'},
               {'label': '加熱', 'text': 'だしで野菜を煮込み、柔らかくなったら豆腐を加える。'},
               {'label': '仕上げ', 'text': '味噌を溶き入れ、ごま油を一滴回しかけて完成。'}]},
    {'slug': 'shijimi-miso',
     'id': 'extra-30',
     'name': 'しじみの味噌汁',
     'category': 'soup',
     'timeMinutes': 15,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'しじみ', 'qty': '200g'},
                     {'name': '豆腐', 'qty': '1/4丁'},
                     {'name': '味噌', 'qty': '大さじ1.5'},
                     {'name': 'だし', 'qty': '400ml'},
                     {'name': '小ねぎ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': 'しじみは砂抜きし、豆腐は角切りにする。'},
               {'label': '加熱', 'text': 'だしを温め、しじみと豆腐を加えてしじみが開くまで煮る。'},
               {'label': '仕上げ', 'text': '味噌を溶き入れ、小ねぎを散らす。'}]},
    {'slug': 'kitsune-udon',
     'id': 'extra-31',
     'name': 'きつねうどん',
     'category': 'soup',
     'timeMinutes': 20,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'うどん', 'qty': '2玉'},
                     {'name': '油揚げ', 'qty': '2枚'},
                     {'name': 'だし', 'qty': '500ml'},
                     {'name': '醤油', 'qty': '大さじ2'},
                     {'name': 'みりん', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': '油揚げは湯通しして細切りにする。'},
               {'label': '加熱', 'text': 'だしに醤油・みりんを加えて煮立て、油揚げを5分煮る。'},
               {'label': '仕上げ', 'text': '別鍋でうどんを茹で、器に盛り、つゆをかける。'}]},
    {'slug': 'takikomi-gohan',
     'id': 'extra-32',
     'name': '炊き込みご飯',
     'category': 'main',
     'timeMinutes': 45,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '米', 'qty': '2合'},
                     {'name': '鶏もも肉', 'qty': '100g'},
                     {'name': 'にんじん', 'qty': '1/3本'},
                     {'name': 'しいたけ', 'qty': '2個'},
                     {'name': '醤油', 'qty': '大さじ2'}],
     'steps': [{'label': '準備', 'text': '米を洗い、水と調味料を加える。鶏肉と野菜は食べやすい大きさに切る。'},
               {'label': '加熱', 'text': '材料を炊飯器に入れ、通常の炊飯モードで炊く。'},
               {'label': '仕上げ', 'text': '混ぜて蒸らし、器に盛る。'}]},
    {'slug': 'ebi-fry',
     'id': 'extra-33',
     'name': 'エビフライ',
     'category': 'main',
     'timeMinutes': 25,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'エビ', 'qty': '8尾'},
                     {'name': '小麦粉', 'qty': '適量'},
                     {'name': '卵', 'qty': '1個'},
                     {'name': 'パン粉', 'qty': '適量'},
                     {'name': 'キャベツ', 'qty': '2枚'}],
     'steps': [{'label': '準備', 'text': 'エビの背わたを取り、塩胡椒をする。小麦粉・卵・パン粉の順に衣をつける。'},
               {'label': '加熱', 'text': '170度の油で2〜3分揚げる。'},
               {'label': '仕上げ', 'text': 'キャベツを添え、タルタルソースをかけて盛る。'}]},
    {'slug': 'korokke',
     'id': 'extra-34',
     'name': 'コロッケ',
     'category': 'side',
     'timeMinutes': 40,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'じゃがいも', 'qty': '3個'},
                     {'name': '合いびき肉', 'qty': '100g'},
                     {'name': '玉ねぎ', 'qty': '1/4個'},
                     {'name': 'パン粉', 'qty': '適量'},
                     {'name': '卵', 'qty': '1個'}],
     'steps': [{'label': '準備', 'text': 'じゃがいもを茹でて潰し、炒めた合いびき肉と玉ねぎを混ぜる。'},
               {'label': '加熱', 'text': '楕円形に成形し、小麦粉・卵・パン粉の順に衣をつける。'},
               {'label': '仕上げ', 'text': '170度の油でこんがり揚げる。'}]},
    {'slug': 'hiyayakko',
     'id': 'extra-35',
     'name': '冷奴',
     'category': 'side',
     'timeMinutes': 5,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '絹ごし豆腐', 'qty': '1丁'},
                     {'name': '小ねぎ', 'qty': '1本'},
                     {'name': '生姜', 'qty': '1片'},
                     {'name': '醤油', 'qty': '大さじ1'}],
     'steps': [{'label': '準備', 'text': '豆腐は水切りして食べやすい大きさに切る。小ねぎと生姜はみじん切りにする。'},
               {'label': '加熱', 'text': '冷蔵庫で冷やしておく。'},
               {'label': '仕上げ', 'text': '器に盛り、生姜と小ねぎをのせ、醤油をかける。'}]},
    {'slug': 'chawanmushi',
     'id': 'extra-36',
     'name': '茶碗蒸し',
     'category': 'side',
     'timeMinutes': 30,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '卵', 'qty': '2個'},
                     {'name': 'だし', 'qty': '300ml'},
                     {'name': '鶏もも肉', 'qty': '50g'},
                     {'name': 'しいたけ', 'qty': '1個'},
                     {'name': 'かまぼこ', 'qty': '2切れ'}],
     'steps': [{'label': '準備', 'text': '卵を溶き、だしと混ぜて茶碗に8分目まで注ぐ。鶏肉・しいたけ・かまぼこを入れる。'},
               {'label': '加熱', 'text': '茶碗にアルミホイルをし、蒸し器または湯せんで15分蒸す。'},
               {'label': '仕上げ', 'text': '竹串を刺して透明な液が出なければ完成。'}]},
    {'slug': 'butter-soy-corn',
     'id': 'extra-37',
     'name': 'バター醤油コーン',
     'category': 'side',
     'timeMinutes': 10,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'とうもろこし', 'qty': '1本'},
                     {'name': 'バター', 'qty': '10g'},
                     {'name': '醤油', 'qty': '小さじ1'},
                     {'name': '黒胡椒', 'qty': '少々'}],
     'steps': [{'label': '準備', 'text': 'とうもろこしは粒を取り出す。'},
               {'label': '加熱', 'text': 'フライパンでバターを溶かし、とうもろこしを炒める。'},
               {'label': '仕上げ', 'text': '醤油を回しかけ、黒胡椒を振って完成。'}]},
    {'slug': 'agedashi-tofu',
     'id': 'extra-38',
     'name': '揚げ出し豆腐',
     'category': 'side',
     'timeMinutes': 20,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': '木綿豆腐', 'qty': '1丁'},
                     {'name': '小麦粉', 'qty': '大さじ2'},
                     {'name': 'だし', 'qty': '200ml'},
                     {'name': '醤油', 'qty': '大さじ1'},
                     {'name': '小ねぎ', 'qty': '適量'}],
     'steps': [{'label': '準備', 'text': '豆腐は水切りし、小麦粉を薄くまぶす。'},
               {'label': '加熱', 'text': '180度の油で表面がきつね色になるまで揚げる。'},
               {'label': '仕上げ', 'text': '器に盛り、温めただしと醤油をかけ、小ねぎを散らす。'}]},
    {'slug': 'kinoko-soba',
     'id': 'extra-39',
     'name': 'きのこそば',
     'category': 'soup',
     'timeMinutes': 20,
     'tags': ['和食'],
     'servings': 2,
     'ingredients': [{'name': 'そば', 'qty': '2玉'},
                     {'name': 'しいたけ', 'qty': '2個'},
                     {'name': 'えのき', 'qty': '1/2袋'},
                     {'name': 'だし', 'qty': '500ml'},
                     {'name': '醤油', 'qty': '大さじ2'}],
     'steps': [{'label': '準備', 'text': 'きのこ類は石づきを取り、食べやすい大きさにする。'},
               {'label': '加熱', 'text': 'だしに醤油・みりんを加えて煮立て、きのこを加えて2分煮る。'},
               {'label': '仕上げ', 'text': '別鍋でそばを茹で、器に盛り、つゆをかける。'}]}
]
